# Generated by Django 2.2.3 on 2020-09-24 01:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 9, 23, 20, 27, 7, 671350))),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField(default=datetime.datetime(2020, 9, 23, 20, 27, 7, 670349))),
                ('endTime', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project')),
            ],
        ),
    ]
