# Generated by Django 2.2.3 on 2020-09-24 05:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField(default=datetime.datetime(2020, 9, 24, 0, 27, 2, 791103))),
                ('endTime', models.DateTimeField()),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 0, 27, 2, 792083)),
        ),
        migrations.DeleteModel(
            name='Tracker',
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Project'),
        ),
    ]
