# Generated by Django 2.2.3 on 2020-09-24 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20200924_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='totalTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='startTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 15, 33, 24, 194719)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 15, 33, 24, 195719)),
        ),
    ]
